MyBookClub/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from users.views import *
from books.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_club.urls')),
    path('', include('users.urls')),
    path('', include('books.urls')),
    path('discussion/', include('book_discussion.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_discussion/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('<int:id>/', discussion, name='discussion'),
]

books/urls.py
from django.urls import path
from .views import *
from .cron import replace

urlpatterns = [
    path('nextbook/', vote_page, name = 'vote_page'),
    path('nextbook/search/', search, name = 'search'),
    path('nextbook/choose/', choose_book, name = 'choose_book'),
    path('nextbook/<int:b_id>/', vote, name = 'votebook'),
    path('replacement/', replace),
    path('read/<int:id>/', readen, name = 'readen'),
    path('nextbook/archive/', archive, name = 'archive'),
]

book_discussion/models.py
from django.db import models
from django.contrib.auth.models import User
from books.models import Book

class BookDiscussion(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True)
    book = models.ForeignKey(Book, on_delete = models.CASCADE, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()
    
    def __str__(self):
        return f'User: {self.user.first_name} | Book: {self.book.title} | Time: {self.date}'

book_discussion/views.py
from django.shortcuts import render, redirect
from books.models import Book
from .models import BookDiscussion
from django.contrib.auth.decorators import login_required

def discussion(request, id):
    book = Book.objects.get(id=id)
    discussions = BookDiscussion.objects.filter(book=id).order_by('-date')
    context = {
        'book': book,
        'discussions': discussions
    }

    if request.method == 'POST':
        if request.user.is_anonymous:
            return redirect('login')
        else:
            comment_text = request.POST.get('comment')
            new_comment = BookDiscussion(
                user = request.user,
                book = book,
                comment = comment_text
            )
            new_comment.save()
            return redirect('discussion', id)

    return render(request, 'discussion.html', context)

book_discussion/templates/discussion.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>

   <div class="row py-3 border-bottom">
      <div class="col-md-6 col-sm-12">
         <div class="row">
            <div class="col-4 text-right">
               <img class="img-thumbnail h-100" src="{{book.image}}">
            </div>
            <div class="col-8 d-flex flex-column">
               <legend class="h4" style="color:rgb(28, 38, 46)">{{ book.title }}</legend>
               <div class="h5 text-dark">{{ book.author }}</div>
               <div class="mt-auto">
                  <a href="{% url 'readen' book.id %}" style="text-decoration:none"><span
                        style="color:rgb(148, 147, 122)">oxudum</span></a>
               </div>
            </div>
         </div>
      </div>
      <div class="col-md-6 d-flex col-sm-12">
         <form action='' method='post' id='comment'>
            {% csrf_token %}
            <fieldset class="form-group">
               <div class="text-dark">
                  Kitab haqda fikrinizi paylaşın:
               </div>
               <div class="input-group">
                  <textarea name="comment" cols="45" rows="3" id="id_comment" name='comment' required></textarea>
               </div>
            </fieldset>
            <div class="input-group-append form group">
               <button type="submit" class="btn px-5 py-0 text-light ml-auto"
                  style="background-color:rgb(68, 110, 55)">göndər</button>
            </div>
         </form>
      </div>
   </div>

   <div class="row">
      <div class="col-md-8 offset-md-2">
         {% for discussion in discussions %}
         <div class='row border-bottom'>
            <div class='col-2 text-center py-2'>
               <img class="rounded-circle" id="user-img-comment" src="{{ discussion.user.profile.image.url }}" alt="">
            </div>
            <div class="col-10 d-flex flex-column">
               <div class='lead'><a href="{% url 'userprofile' discussion.user.id %}" style="text-decoration:none"><span style="color:rgb(31, 117, 28);">{{ discussion.user.first_name }}  {{discussion.user.last_name}}:</span></a></div>
               <p class='text-dark'> {{ discussion.comment }}</p>
               <div>
                  <div class="ml-auto">
                  <span class='text-muted small'>{{ discussion.date }}</span>
               </div>
            </div>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
</div>
{% endblock content %}